const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const mime={'.html':'text/html;charset=utf-8','.js':'application/javascript;charset=utf-8','.css':'text/css;charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'};
function server(){return http.createServer((req,res)=>{let name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/my-fitness-plan\//,'');if(!name||name.endsWith('/'))name+='index.html';const file=path.resolve(root,name);if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,data)=>{res.writeHead(err?404:200,{'Content-Type':mime[path.extname(file)]||'text/plain','Cache-Control':'no-cache'});res.end(err?'not found':data);});});}
(async()=>{const srv=server();await new Promise(r=>srv.listen(4173,'127.0.0.1',r));if(process.argv.includes('--serve')){console.log('Preview http://127.0.0.1:4173/my-fitness-plan/');return;}
const browser=await chromium.launch({channel:'chrome',headless:true});let count=0;const ok=s=>{count++;console.log('PASS '+s);};const out=process.env.ARTIFACT_DIR||path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true,timezoneId:'Asia/Shanghai',acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:4173/my-fitness-plan/';
try{
await page.goto(url);await page.locator('[data-exercise=pulldown]').waitFor();await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.locator('[data-exercise=pulldown]').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'手机端-训练首页.png'),fullPage:false});ok('390px mobile layout and PWA initialization');
await page.getByRole('button',{name:'教学 ↗'}).first().click();await page.locator('dialog[open] svg').waitFor();await page.screenshot({path:path.join(out,'手机端-动作教学.png')});await page.getByRole('button',{name:'关闭教学'}).click();ok('exercise teaching dialog opens and closes');
const first=page.locator('[data-exercise=pulldown]');await first.locator('[data-field=weight]').first().fill('10');await first.locator('[data-field=reps]').first().fill('12');await first.locator('[data-field=rpe]').first().fill('7.5');await first.locator('[data-field=done]').first().check();await page.getByRole('button',{name:'完成训练 · 打卡'}).click();assert.match(await page.locator('#muscle-card').innerText(),/背部/);await page.reload();assert.equal(await page.locator('[data-exercise=pulldown] [data-field=weight]').first().inputValue(),'10');assert.equal(await page.locator('[data-exercise=pulldown] [data-field=done]').first().isChecked(),true);ok('set entry, check-in, muscle map and reload persistence');
await page.locator('#daily-note').fill('没睡好，只有哑铃，今天时间少');assert.match(await page.locator('#rules').innerText(),/疲劳/);assert.match(await page.locator('#rules').innerText(),/哑铃/);await page.locator('[data-exercise=pulldown] [data-select=prone]').first().click();assert.equal(await page.locator('[data-exercise=prone]').count(),1);assert.equal(await page.evaluate(()=>Object.values(JSON.parse(localStorage.shape8w_v2).sessions)[0].logs.pulldown.sets[0].weight),10);ok('instant note recommendation and replacement preserves previous exercise logs');
await page.locator('#daily-note').fill('肩膀疼，头晕');assert.match(await page.locator('#rules').innerText(),/暂停/);assert.match(await page.locator('.advice').first().innerText(),/暂停/);await page.locator('#daily-note').fill('状态正常');ok('pain overrides load progression');
await page.locator('[data-tab=calendar]').click();assert.equal(await page.locator('.calendar-day.checked').count(),1);await page.screenshot({path:path.join(out,'手机端-健身日历.png')});await page.locator('[data-action=month-prev]').click();await page.locator('[data-action=month-next]').click();ok('calendar month navigation and dated check-in');
await page.locator('[data-tab=body]').click();await page.locator('[name=weight]').fill('48.5');await page.locator('[name=waist]').fill('65.2');await page.locator('[name=thigh]').fill('49.1');await page.getByRole('button',{name:'保存身体记录'}).click();assert.equal(await page.locator('.history tbody tr').count(),1);await page.locator('[data-metric=waist]').click();assert.equal(await page.locator('.chart circle').count(),1);await page.screenshot({path:path.join(out,'手机端-身体记录.png')});ok('body measurements and chart persist without inventing historic baseline');
await page.locator('[data-tab=settings]').click();const waitDownload=page.waitForEvent('download');await page.getByRole('button',{name:'导出完整备份 JSON'}).click();const download=await waitDownload;const downloadPath=await download.path();const backup=JSON.parse(fs.readFileSync(downloadPath,'utf8'));assert.equal(Object.keys(backup.data.measurements).length,1);await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.getByRole('button',{name:'确认恢复'}).click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.shape8w_v2).version),2);await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":900}')});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('无法导入'));assert.match(await page.locator('#toast').innerText(),/无法导入/);ok('JSON export, validated restore, invalid-file rejection');
await context.setOffline(true);await page.reload();await page.locator('[data-exercise=prone]').waitFor();await page.locator('[data-tab=body]').click();assert.equal(await page.locator('.history tbody tr').count(),1);await context.setOffline(false);ok('offline reload retains app and records at GitHub Pages subpath');
await page.locator('[data-tab=train]').click();await page.locator('[data-action=next]').click();assert.equal(await page.locator('[data-field=done]').first().isDisabled(),true);await page.locator('[data-action=today]').click();await page.locator('[data-action=timer]').click();await page.waitForTimeout(1200);assert.notEqual(await page.locator('#timer-value').innerText(),'01:30');await page.locator('[data-action=timer-reset]').click();assert.equal(await page.locator('#timer-value').innerText(),'01:30');ok('future records disabled and timestamp-based rest timer');
for(const width of [320,375,430,768,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`);}ok('no horizontal overflow at 320, 375, 390, 430, 768, 1280px');for(const section of ['calendar','body','settings']){await page.setViewportSize({width:320,height:740});await page.locator('[data-tab='+section+']').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'320px overflow on '+section);}ok('all pages fit 320px including measurement table');
const corrupt=await browser.newContext();await corrupt.addInitScript(()=>localStorage.setItem('shape8w_v2','{broken'));const corruptPage=await corrupt.newPage();await corruptPage.goto(url);assert.equal(await corruptPage.locator('#storage-warning').isVisible(),true);assert.equal(await corruptPage.evaluate(()=>localStorage.getItem('shape8w_v2')),'{broken');await corrupt.close();ok('corrupt storage protected without silent overwrite');
const fail=await browser.newContext();await fail.addInitScript(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='shape8w_v2')throw new DOMException('full','QuotaExceededError');return set.call(this,k,v);};});const failPage=await fail.newPage();await failPage.goto(url);await failPage.locator('#daily-note').fill('很累');assert.match(await failPage.locator('#storage-warning').innerText(),/保存失败/);await fail.close();ok('quota failure has persistent visible warning');
assert.deepEqual(errors,[]);ok('no uncaught browser errors');console.log(`${count} browser checks passed`);
}finally{await browser.close();await new Promise(r=>srv.close(r));}
})().catch(e=>{console.error(e);process.exit(1);});

